@baseUrl = https://localhost:7115
@token = paste-access-token-here
@productId = 1
@categoryId = 1

### Update Product
PUT {{baseUrl}}/api/v1/products/{{productId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Product",
  "description": "Updated description",
  "price": 49.99,
  "categoryId": {{categoryId}}
}

