@baseUrl = https://localhost:7115
@token = paste-access-token-here
@refreshToken = paste-refresh-token-here

### Revoke Refresh Token
POST {{baseUrl}}/api/v1/auth/revoke
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

