@WebApi_HostAddress = http://localhost:5266

GET {{WebApi_HostAddress}}/health
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123!"
}

###

GET {{WebApi_HostAddress}}/api/v1/products
Accept: application/json

###
